### ISSUE TITLE
Trying to update this

### ISSUE THREAD

**Issue by miguel-apereira** [giacomozama/club-penguin-legacy-trainer#1]
Hey!

I've been trying to update this code, but even though I changed to URL's for the correct ones, I'm still having trouble on making the local server work. If you have the time and the interest, we could both check it out!

**Comment by giacomozama** [comment]
Hey! I honestly never expected anyone would be interested in this.

There were indeed a couple missing imports in server.js I didn't catch before, for some reason. I did also update the URLs and it's working for me now. Does it work for you?

**Comment by miguel-apereira** [comment]
It worked like a charm!
I'm too old for this game now, but played quite alot in my childhood. 
Very insteresting to see how you've achieve this!
Quick question, what would be the best way to figure out the swf parameters to edit?

**Comment by giacomozama** [comment]
You can use a decompiler such as JPEXS and look at how ActionScript matches P-code to figure out what to edit.

Unfortunately, this only works on AS2 stuff (minigames, basically) as Flasm can't really handle AS3, but I'm trying to figure out whether there are other ways to hack AS3 stuff along with Flash based private servers.

**Comment by miguel-apereira** [comment]
Good guidance, I will have a deeper look into this, seems very interesting :)

**Comment by miguel-apereira** [comment]
One thing I'm having trouble figuring out is for example on the CatchingWaves game, how do you know that are the lines 9848 to 9856 that you have to replace? 
In JPEXS I saw the changes you've made with Flasm, but the code lines do not match to what it is on the JS.
Did you export the game as one single code file?
