### ISSUE TITLE
Item Adder

### ISSUE THREAD

**Issue by SlimF** [giacomozama/club-penguin-legacy-trainer#2]
Hey, I was wondering if an item adder would be possible?

Also, from my quick test, it runs fine on Windows!

**Comment by giacomozama** [comment]
Speaking of CPL specifically, all of the stuff I checked which adds items to your inventory was ported to HTML5 so I don't know if an item adder can be made by patching SWFs, and I currently don't know other techniques. I believe you can probably pull it off on some Flash based CPPS.

Also, for most of OG Club Penguin's lifespan you could only permanently hack items which were available through legit means. If that is still the case then item adders are as useless as they were back then, unfortunately.

**Comment by SlimF** [comment]
Ahh I see, thank you for letting me know! Closing this, have a nice day!
